# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/LibreGrid',
                'doc_host': 'https://PlutoPowerClub.github.io',
                'git_url': 'https://github.com/PlutoPowerClub/LibreGrid',
                'lib_path': 'LibreGrid'},
  'syms': { 'LibreGrid.core': {'LibreGrid.core.get_smart_meter_data': ('core.html#get_smart_meter_data', 'LibreGrid/core.py')},
            'LibreGrid.fomantic': { 'LibreGrid.fomantic.Column': ('fomantic.html#column', 'LibreGrid/fomantic.py'),
                                    'LibreGrid.fomantic.Grid': ('fomantic.html#grid', 'LibreGrid/fomantic.py'),
                                    'LibreGrid.fomantic.HeroSegment': ('fomantic.html#herosegment', 'LibreGrid/fomantic.py'),
                                    'LibreGrid.fomantic.Segment': ('fomantic.html#segment', 'LibreGrid/fomantic.py'),
                                    'LibreGrid.fomantic.VerticalStripeSegment': ( 'fomantic.html#verticalstripesegment',
                                                                                  'LibreGrid/fomantic.py')}}}
