# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['get_smart_meter_data']

# %% ../nbs/00_core.ipynb 2
import httpx
import os

# %% ../nbs/00_core.ipynb 3
def get_smart_meter_data():
    "Python function to get smart meter data from Octopus Home Mini API"
    OE_API_KEY = os.getenv("OE_API_KEY")
    # TODO
